const users = [
  {
    name: 'Nitha Pandaran',
    bettedCountries: [
      'Portugal',
      'France',
      'Denmark',
      'Mexico',
      'Senegal',
      'Croatia',
      'Korea Republic',
      'Nigeria',
    ],
  },
  {
    name: 'Denis McLean',
    bettedCountries: [
      'Germany',
      'Belgium',
      'Switzerland',
      'Uruguay',
      'Iran',
      'Croatia',
      'Australia',
      'Nigeria',
    ],
  },
  {
    name: 'Peti',
    bettedCountries: [
      'Germany',
      'Belgium',
      'Denmark',
      'Uruguay',
      'Senegal',
      'Croatia',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Craig Stein',
    bettedCountries: [
      'Germany',
      'Belgium',
      'Switzerland',
      'Uruguay',
      'Iran',
      'Croatia',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Juan Medina',
    bettedCountries: [
      'Brazil',
      'France',
      'Denmark',
      'Uruguay',
      'Egypt',
      'Croatia',
      'Korea Republic',
      'Nigeria',
    ],
  },
  {
    name: 'Ginney Miranda',
    bettedCountries: [
      'Brazil',
      'Belgium',
      'Iceland',
      'Uruguay',
      'Iran',
      'England',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Vic Marasco',
    bettedCountries: [
      'Brazil',
      'Poland',
      'Denmark',
      'Mexico',
      'Iran',
      'Croatia',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Gabi Bayer',
    bettedCountries: [
      'Germany',
      'Spain',
      'Denmark',
      'Uruguay',
      'Tunisia',
      'Serbia',
      'Japan',
      'Nigeria',
    ],
  },
  {
    name: 'Robin Lybarger',
    bettedCountries: [
      'Germany',
      'France',
      'Switzerland',
      'Uruguay',
      'Senegal',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Angie Johnson',
    bettedCountries: [
      'Germany',
      'Belgium',
      'Denmark',
      'Mexico',
      'Senegal',
      'England',
      'Australia',
      'Morocco',
    ],
  },
  {
    name: 'Alanna Craige',
    bettedCountries: [
      'Germany',
      'Spain',
      'Switzerland',
      'Uruguay',
      'Tunisia',
      'Croatia',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Magda Craige',
    bettedCountries: [
      'Germany',
      'Spain',
      'Iceland',
      'Uruguay',
      'Senegal',
      'England',
      'Australia',
      'Nigeria',
    ],
  },
  {
    name: 'Dave Kreiner',
    bettedCountries: [
      'Brazil',
      'Spain',
      'Switzerland',
      'Mexico',
      'Senegal',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Andy Stuart',
    bettedCountries: [
      'Germany',
      'France',
      'Switzerland',
      'Mexico',
      'Senegal',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Nancy Bray',
    bettedCountries: [
      'Germany',
      'France',
      'Switzerland',
      'Mexico',
      'Senegal',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Ilcsi Kubrizcky',
    bettedCountries: [
      'Argentina',
      'Spain',
      'Sweden',
      'Uruguay',
      'Senegal',
      'England',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Rogelio Castaneda',
    bettedCountries: [
      'Germany',
      'France',
      'Switzerland',
      'Colombia',
      'Egypt',
      'England',
      'Japan',
      'Nigeria',
    ],
  },
  {
    name: 'Prasad Hebbar',
    bettedCountries: [
      'Germany',
      'Spain',
      'Sweden',
      'Colombia',
      'Senegal',
      'Croatia',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Juan Manuel Delgado',
    bettedCountries: [
      'Brazil',
      'France',
      'Denmark',
      'Uruguay',
      'Egypt',
      'England',
      'Korea Republic',
      'Peru',
    ],
  },
  {
    name: 'Peter Boyle',
    bettedCountries: [
      'Argentina',
      'France',
      'Denmark',
      'Uruguay',
      'Egypt',
      'England',
      'Japan',
      'Morocco',
    ],
  },
  {
    name: 'Sami Sharokhi',
    bettedCountries: [
      'Portugal',
      'Belgium',
      'Switzerland',
      'Colombia',
      'Iran',
      'England',
      'Australia',
      'Morocco',
    ],
  },
  {
    name: 'Brent Craige',
    bettedCountries: [
      'Brazil',
      'France',
      'Iceland',
      'Mexico',
      'Egypt',
      'England',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Jennifer & Leo Perez del Burgo',
    bettedCountries: [
      'Germany',
      'France',
      'Switzerland',
      'Colombia',
      'Senegal',
      'Croatia',
      'Panama',
      'Peru',
    ],
  },
  {
    name: 'Chris Hauck',
    bettedCountries: [
      'Germany',
      'Belgium',
      'Denmark',
      'Colombia',
      'Senegal',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Nick Ede',
    bettedCountries: [
      'Argentina',
      'Spain',
      'Switzerland',
      'Uruguay',
      'Senegal',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Vanessa Craige',
    bettedCountries: [
      'Germany',
      'Belgium',
      'Iceland',
      'Uruguay',
      'Egypt',
      'England',
      'Japan',
      'Morocco',
    ],
  },
  {
    name: 'Piyush Gour',
    bettedCountries: [
      'Germany',
      'Spain',
      'Switzerland',
      'Mexico',
      'Senegal',
      'England',
      'Korea Republic',
      'Peru',
    ],
  },
  {
    name: 'Viki Kubrizcky',
    bettedCountries: [
      'Germany',
      'Spain',
      'Switzerland',
      'Colombia',
      'Egypt',
      'Croatia',
      'Australia',
      'Nigeria',
    ],
  },
  {
    name: 'Tom Dombrowsky',
    bettedCountries: [
      'Germany',
      'France',
      'Switzerland',
      'Colombia',
      'Egypt',
      'England',
      'Australia',
      'Nigeria',
    ],
  },
  {
    name: 'Dani Kubrizcky',
    bettedCountries: [
      'Argentina',
      'France',
      'Denmark',
      'Uruguay',
      'Egypt',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Joe Kubrizcky',
    bettedCountries: [
      'Argentina',
      'Spain',
      'Switzerland',
      'Uruguay',
      'Egypt',
      'England',
      'Japan',
      'Peru',
    ],
  },
  {
    name: 'Scott Patton',
    bettedCountries: [
      'Germany',
      'Spain',
      'Switzerland',
      'Colombia',
      'Tunisia',
      'Croatia',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Jose Becerril',
    bettedCountries: [
      'Germany',
      'Spain',
      'Iceland',
      'Mexico',
      'Egypt',
      'England',
      'Australia',
      'Peru',
    ],
  },
  {
    name: 'Vijay Nagasubramanian',
    bettedCountries: [
      'Argentina',
      'Belgium',
      'Switzerland',
      'Colombia',
      'Egypt',
      'England',
      'Korea Republic',
      'Peru',
    ],
  },
  {
    name: 'Jorge Castiglione',
    bettedCountries: [
      'Argentina',
      'Spain',
      'Sweden',
      'Costa Rica',
      'Senegal',
      'England',
      'Korea Republic',
      'Peru',
    ],
  },
];

module.exports = {
  users,
};
