const users = [
  {
    name: 'Alanna',
    bettedCountries: [
      'France',
      'Germany',
      'England',
      'Uruguay',
      'Ecuador',
      'Morocco',
      'Serbia',
      'Iran',
    ],
  },
  {
    name: 'Alonso',
    bettedCountries: [
      'France',
      'Argentina',
      'Denmark',
      'Uruguay',
      'Japan',
      'Cameroon',
      'Serbia',
      'Iran',
    ],
  },
  {
    name: 'Andy',
    bettedCountries: [
      'France',
      'Brazil',
      'Denmark',
      'Mexico',
      'Ecuador',
      'Morocco',
      'Wales',
      'Ghana',
    ],
  },
  {
    name: 'Angie',
    bettedCountries: [
      'Netherlands',
      'Germany',
      'England',
      'Mexico',
      'Australia',
      'Senegal',
      'Costa Rica',
      'Iran',
    ],
  },
  {
    name: 'Ariel',
    bettedCountries: [
      'France',
      'Germany',
      'England',
      'Mexico',
      'Japan',
      'Senegal',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'Brent',
    bettedCountries: [
      'Netherlands',
      'Germany',
      'England',
      'Mexico',
      'Ecuador',
      'Tunisia',
      'Serbia',
      'Qatar',
    ],
  },
  {
    name: 'Chris',
    bettedCountries: [
      'France',
      'Germany',
      'England',
      'Mexico',
      'Ecuador',
      'Senegal',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'Craig',
    bettedCountries: [
      'France',
      'Germany',
      'England',
      'Uruguay',
      'Ecuador',
      'Senegal',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'Dani',
    bettedCountries: [
      'Spain',
      'Argentina',
      'England',
      'Uruguay',
      'Japan',
      'Senegal',
      'Wales',
      'Qatar',
    ],
  },
  {
    name: 'Dave',
    bettedCountries: [
      'Spain',
      'Brazil',
      'Denmark',
      'Uruguay',
      'Ecuador',
      'Senegal',
      'Poland',
      'Iran',
    ],
  },
  {
    name: 'Ella',
    bettedCountries: [
      'Spain',
      'Germany',
      'Switzerland',
      'Uruguay',
      'Australia',
      'Morocco',
      'Costa Rica',
      'Iran',
    ],
  },
  {
    name: 'Gabi',
    bettedCountries: [
      'Belgium',
      'Brazil',
      'Denmark',
      'USA',
      'South Korea',
      'Senegal',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'Ginney',
    bettedCountries: [
      'Spain',
      'Brazil',
      'England',
      'USA',
      'Australia',
      'Morocco',
      'Costa Rica',
      'Iran',
    ],
  },
  {
    name: 'Gordon',
    bettedCountries: [
      'Spain',
      'Argentina',
      'England',
      'Uruguay',
      'Japan',
      'Senegal',
      'Serbia',
      'Iran',
    ],
  },
  {
    name: 'Ilcsi',
    bettedCountries: [
      'Spain',
      'Argentina',
      'Croatia',
      'Uruguay',
      'Japan',
      'Cameroon',
      'Wales',
      'Qatar',
    ],
  },
  {
    name: 'Janice',
    bettedCountries: [
      'France',
      'Brazil',
      'England',
      'Uruguay',
      'Ecuador',
      'Cameroon',
      'Wales',
      'Qatar',
    ],
  },
  {
    name: 'Jennifer',
    bettedCountries: [
      'Spain',
      'Brazil',
      'Denmark',
      'Uruguay',
      'Ecuador',
      'Morocco',
      'Serbia',
      'Iran',
    ],
  },
  {
    name: 'Joe',
    bettedCountries: [
      'Netherlands',
      'Argentina',
      'Denmark',
      'Uruguay',
      'Japan',
      'Morocco',
      'Serbia',
      'Iran',
    ],
  },
  {
    name: 'Magda',
    bettedCountries: [
      'France',
      'Germany',
      'Croatia',
      'Uruguay',
      'South Korea',
      'Senegal',
      'Poland',
      'Iran',
    ],
  },
  {
    name: 'MikeM',
    bettedCountries: [
      'Netherlands',
      'Brazil',
      'England',
      'Uruguay',
      'Ecuador',
      'Senegal',
      'Serbia',
      'Ghana',
    ],
  },
  {
    name: 'MikeW',
    bettedCountries: [
      'Belgium',
      'Brazil',
      'England',
      'Uruguay',
      'Ecuador',
      'Senegal',
      'Serbia',
      'Ghana',
    ],
  },
  {
    name: 'Nancy',
    bettedCountries: [
      'France',
      'Argentina',
      'England',
      'Mexico',
      'Australia',
      'Senegal',
      'Serbia',
      'Saudi Arabia',
    ],
  },
  {
    name: 'Niall',
    bettedCountries: [
      'France',
      'Brazil',
      'Croatia',
      'Mexico',
      'South Korea',
      'Senegal',
      'Costa Rica',
      'Iran',
    ],
  },
  {
    name: 'Paolo',
    bettedCountries: [
      'Spain',
      'Brazil',
      'Denmark',
      'Uruguay',
      'Ecuador',
      'Morocco',
      'Serbia',
      'Qatar',
    ],
  },
  {
    name: 'Paul',
    bettedCountries: [
      'Netherlands',
      'Brazil',
      'England',
      'USA',
      'Japan',
      'Cameroon',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'PeterB',
    bettedCountries: [
      'France',
      'Argentina',
      'England',
      'Canada',
      'South Korea',
      'Senegal',
      'Wales',
      'Ghana',
    ],
  },
  {
    name: 'PeterU',
    bettedCountries: [
      'France',
      'Brazil',
      'England',
      'Uruguay',
      'Ecuador',
      'Senegal',
      'Poland',
      'Iran',
    ],
  },
  {
    name: 'Rogelio',
    bettedCountries: [
      'France',
      'Brazil',
      'Switzerland',
      'Uruguay',
      'Japan',
      'Senegal',
      'Wales',
      'Qatar',
    ],
  },
  {
    name: 'Sami',
    bettedCountries: [
      'Belgium',
      'Argentina',
      'Switzerland',
      'Uruguay',
      'Japan',
      'Tunisia',
      'Wales',
      'Iran',
    ],
  },
  {
    name: 'Scott',
    bettedCountries: [
      'France',
      'Brazil',
      'England',
      'Canada',
      'Japan',
      'Senegal',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'Thomas',
    bettedCountries: [
      'France',
      'Brazil',
      'England',
      'USA',
      'Ecuador',
      'Senegal',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'Tom',
    bettedCountries: [
      'Netherlands',
      'Argentina',
      'Denmark',
      'Uruguay',
      'Japan',
      'Morocco',
      'Wales',
      'Ghana',
    ],
  },
  {
    name: 'Vanessa',
    bettedCountries: [
      'France',
      'Brazil',
      'England',
      'Uruguay',
      'Ecuador',
      'Senegal',
      'Wales',
      'Ghana',
    ],
  },
  {
    name: 'Vijay',
    bettedCountries: [
      'France',
      'Brazil',
      'England',
      'Uruguay',
      'Ecuador',
      'Morocco',
      'Poland',
      'Ghana',
    ],
  },
  {
    name: 'Viki',
    bettedCountries: [
      'Spain',
      'Brazil',
      'England',
      'Mexico',
      'Japan',
      'Senegal',
      'Wales',
      'Iran',
    ],
  },
  {
    name: 'Vince',
    bettedCountries: [
      'France',
      'Brazil',
      'Croatia',
      'Uruguay',
      'Japan',
      'Cameroon',
      'Poland',
      'Qatar',
    ],
  },
];

module.exports = {
  users,
};
